#ifndef PROJECT_CONF_H
#define PROJECT_CONF_H

#define NETSTACK_CONF_MAC_MAX_CSMA_BACKOFF 4

#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_APP LOG_LEVEL_DBG

#define SAMPLE_INTERVAL (CLOCK_SECOND / 2)
#define WINDOW_SIZE 10
#define NEIGHBOR_TIMEOUT (CLOCK_SECOND * 3)
#define MAX_NEIGHBORS 10

#define FIXED_SCALE 64

#endif
